apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      # ðŸ‘‡ THIS IS THE NEW SECTION THAT USES YOUR SECRET
      imagePullSecrets:
        - name: dockerhub-creds
      # ðŸ‘† END OF NEW SECTION
      containers:
        - name: library-app-container
          image: konderaju1238/library-management-system:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/librarydatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: libraryuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: Library@123
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update